$_DBCONFIG['host'] = 'db'; // This is normally set to localhost
$_DBCONFIG['database'] = 'dev'; // Database name
$_DBCONFIG['tablePrefix'] = 'contrexx_'; // Database table prefix
$_DBCONFIG['user'] = 'root'; // Database username
$_DBCONFIG['password'] = '123456'; // Database password
$_DBCONFIG['dbType'] = 'mysql';    // Database type (e.g. mysql,postgres ..)
$_DBCONFIG['charset'] = 'utf8'; // Charset (default, latin1, utf8, ..)
$_DBCONFIG['timezone'] = 'UTC'; // Controller's timezone for model
$_DBCONFIG['collation'] = 'utf8_unicode_ci';
